### ISSUE TITLE
Module-6 connecting.ipynb. Unable to interact with the deploy agent.

### ISSUE THREAD

**Issue by cris-m** [langchain-ai/langchain-academy#70]
I am using anthropic Claude model but everytime I sent message to the remote graph. I get the following exception:

```
Traceback (most recent call last):
  File "/api/langgraph_api/queue.py", line 156, in worker
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 489, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/api/langgraph_api/stream.py", line 280, in consume
  File "/api/langgraph_api/stream.py", line 270, in consume
  File "/api/langgraph_api/stream.py", line 221, in astream_state
  File "/api/langgraph_api/asyncio.py", line 67, in wait_if_not_done
  File "/usr/local/lib/python3.11/site-packages/langgraph/pregel/__init__.py", line 1867, in astream
    async for * in runner.atick(
  File "/usr/local/lib/python3.11/site-packages/langgraph/pregel/runner.py", line 288, in atick
    *panic_or_proceed(
  File "/usr/local/lib/python3.11/site-packages/langgraph/pregel/runner.py", line 370, in *panic*or_proceed
    raise exc
  File "/usr/local/lib/python3.11/site-packages/langgraph/pregel/retry.py", line 138, in arun_with_retry
    await task.proc.ainvoke(task.input, config)
  File "/usr/local/lib/python3.11/site-packages/langgraph/utils/runnable.py", line 453, in ainvoke
    input = await asyncio.create_task(coro, context=context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langgraph/utils/runnable.py", line 236, in ainvoke
    ret = await asyncio.create_task(coro, context=context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langchain_core/runnables/config.py", line 588, in run_in_executor
    return await asyncio.get_running_loop().run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langchain_core/runnables/config.py", line 579, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/deps/__outer_deployment/src/task_maistro.py", line 253, in task_mAIstro
    memories = store.search(namespace)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langgraph/store/base/__init__.py", line 569, in search
    return self.batch([SearchOp(namespace_prefix, filter, limit, offset, query)])[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langgraph_storage/store.py", line 39, in batch
    if self._loop is asyncio.get_running_loop():
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: no running event loop
During task with name 'task_mAIstro' and id '31907da4-76fe-8dcd-8cba-56985b6f571e'
```

The error is relate to the store.

I have test both the langgraph-sdk and LangGraph Studio but I still get the same issue.

```python
from langgraph_sdk import get_client
from langgraph.pregel.remote import RemoteGraph
from langchain_core.messages import convert_to_messages
from langchain_core.messages import HumanMessage, SystemMessage

url_for_cli_deployment = "http://localhost:8123"
client = get_client(url=url_for_cli_deployment)

url = "http://localhost:8123"
graph_name = "task_maistro" 
remote_graph = RemoteGraph(graph_name, url=url)

thread = await client.threads.create()user_input = "Add a ToDo to finish booking travel to Hong Kong by end of next week. Also, add a ToDo to call parents back about Thanksgiving plans."
config = {"configurable": {"user_id": "Test"}}
graph_name = "task_maistro" 
run = await client.runs.create(thread["thread_id"], graph_name, input={"messages": [HumanMessage(content=user_input)]}, config=config)
```

**Comment by cris-m** [comment]
Without deploy, I test the example of `task_maistro` code in `notebook` and everything work perfectly

**Comment by cris-m** [comment]
I have fix the issue. I guess we have to modify the tutorial. I had to use `async`

```python
 memories = await store.asearch(namespace)
```
