### ISSUE TITLE
Error running module 5 in studio: RuntimeError('no running event loop')

### ISSUE THREAD

**Issue by Liboul** [langchain-ai/langchain-academy#71]
Running the `chatbot_memory` agent in studio triggers an error `RuntimeError('no running event loop')`.

<img width="706" alt="image" src="https://github.com/user-attachments/assets/00fd6f96-80d4-464f-b91c-642d010a5c0b">

Here's the stacktrace:
```
langgraph-api-1       | error | Background run failed | Traceback (most recent call last):
  File "/api/langgraph_api/queue.py", line 156, in worker
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 489, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/api/langgraph_api/stream.py", line 280, in consume
  File "/api/langgraph_api/stream.py", line 270, in consume
  File "/api/langgraph_api/stream.py", line 221, in astream_state
  File "/api/langgraph_api/asyncio.py", line 67, in wait_if_not_done
  File "/usr/local/lib/python3.11/site-packages/langgraph/pregel/__init__.py", line 1867, in astream
    async for _ in runner.atick(
  File "/usr/local/lib/python3.11/site-packages/langgraph/pregel/runner.py", line 288, in atick
    _panic_or_proceed(
  File "/usr/local/lib/python3.11/site-packages/langgraph/pregel/runner.py", line 370, in _panic_or_proceed
    raise exc
  File "/usr/local/lib/python3.11/site-packages/langgraph/pregel/retry.py", line 138, in arun_with_retry
    await task.proc.ainvoke(task.input, config)
  File "/usr/local/lib/python3.11/site-packages/langgraph/utils/runnable.py", line 453, in ainvoke
    input = await asyncio.create_task(coro, context=context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langgraph/utils/runnable.py", line 236, in ainvoke
    ret = await asyncio.create_task(coro, context=context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langchain_core/runnables/config.py", line 588, in run_in_executor
    return await asyncio.get_running_loop().run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langchain_core/runnables/config.py", line 579, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthieulibeer/workspace/langgraph-academy/module-5/studio/memory_store.py", line 51, in call_model
    existing_memory = store.get(namespace, key)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langgraph/store/base/__init__.py", line 545, in get
    return self.batch([GetOp(namespace, key)])[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langgraph_storage/store.py", line 39, in batch
    if self._loop is asyncio.get_running_loop():
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
```

This was not the case until Friday Dec 6th.
The notebook for the same agent, including the `store.search` call, runs smoothly.

Same thing on our private project, any call to `store.search` fails in studio since the downtime on Friday Dec 6th, nothing changed otherwise. I'm not the only one impacted, a friend of mine has the exact same issue since Friday as well.

Setup:
- Macbook Pro M1 chip
- Version 0.31 of Langgraph Studio
- Docker Desktop Version 4.35.1
- Docker Compose version v2.29.7-desktop.1

**Comment by Liboul** [comment]
Thanks!
